### PR TITLE
October's progress (as of now)

### PR DESCRIPTION
**Pull request by Guibi1**
Here's a summary of what I did:

- Reformated a lot of code
- Integrated what I did in the `CRCRME Stage Form Demo` repo (json and files to parse it)
- Cleaned up a small chunk of `CRCRME Enhanced Containers`
- Added `AppLocalizations` with `l10n` but I did not translate the entire app yet
- Created `FormService` to facilitate form validation (regex)
- Began to work on the students screens
- F*cked the commit history because I wanted to remove the first version on the json mentioned above

- - -
This change is [Reviewable](https://reviewable.io/reviews/cr-crme/banque_stages/4)

### CODE REVIEW

**Comment by Guibi1** [comment]
As I feared. Conflicts do reslove but no actual merge conflicts in the files... We might need to force push....

**Comment by pariterre** [comment]
How come there is so much conflicts??

**Review by pariterre — CHANGES_REQUESTED** [review]
What should we expect for the other students if we force push?

> Reviewed 83 of 83 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cr-crme/banque_stages/4#-:-NEulOb_7DwkZt-6tL1x:b-pou2yu)* status: all files reviewed, 6 unresolved discussions (waiting on @Guibi1)

___
*[`lib/common/providers/students_provider.dart` line 9 at r1](https://reviewable.io/reviews/cr-crme/banque_stages/4#-NEufV7fCHxb9_0aPYLd:-NEufV7fCHxb9_0aPYLe:b-v15jfe) ([raw file](https://github.com/cr-crme/banque_stages/blob/0c33dd257aadaf468611458ca9ba7f8b65bf4889/lib/common/providers/students_provider.dart#L9)):*
> ```Dart
>       : super(
>           pathToData: "students",
>           pathToAvailableDataIds: "void",
> ```

Is `void` a new keyword to ignore this feature? :)
___
*[`lib/common/widgets/activity_type_cards.dart` line 5 at r1](https://reviewable.io/reviews/cr-crme/banque_stages/4#-NEufc3C1DqdzRdbjSLn:-NEufc3C1DqdzRdbjSLo:bxhhjes) ([raw file](https://github.com/cr-crme/banque_stages/blob/0c33dd257aadaf468611458ca9ba7f8b65bf4889/lib/common/widgets/activity_type_cards.dart#L5)):*
> ```Dart
> class ActivityTypeCards extends StatelessWidget {
>   const ActivityTypeCards({
>     super.key,
> ```

Is this the new recommended way? That looks neat
___
*[`lib/common/widgets/main_drawer.dart` line 18 at r1](https://reviewable.io/reviews/cr-crme/banque_stages/4#-NEufnMRCAlIHpIANNPI:-NEufnMRCAlIHpIANNPJ:bsc59zo) ([raw file](https://github.com/cr-crme/banque_stages/blob/0c33dd257aadaf468611458ca9ba7f8b65bf4889/lib/common/widgets/main_drawer.dart#L18)):*
> ```Dart
>       builder: (context, provider, _) => Drawer(
>         child: Scaffold(
>           appBar: AppBar(title: const Text("Banque de Stages")),
> ```

As I was discussing with Aurélie, it may happen in the future that the app should be available in english. I therefore suggest that we create a structure that holds all the texts and to refer to that structure, hence regrouping all pieces of text to the same place. Then using a selector the return the right value
___
*[`lib/localizations/app_en.arb` line 2 at r1](https://reviewable.io/reviews/cr-crme/banque_stages/4#-NEuh30g02ZDoilkvbSQ:-NEuh30g02ZDoilkvbSR:b-yzkx4) ([raw file](https://github.com/cr-crme/banque_stages/blob/0c33dd257aadaf468611458ca9ba7f8b65bf4889/lib/localizations/app_en.arb#L2)):*
> ```
> {
>     "@@locale": "en",
> ```

Oh! There it is... 
___
*[`lib/localizations/app_en.arb` line 4 at r1](https://reviewable.io/reviews/cr-crme/banque_stages/4#-NEuhi18B6fcDLSstIGe:-NEuhi18B6fcDLSstIGf:b-gb91y7) ([raw file](https://github.com/cr-crme/banque_stages/blob/0c33dd257aadaf468611458ca9ba7f8b65bf4889/lib/localizations/app_en.arb#L4)):*
> ```
>     "@@locale": "en",
>     "appName": "Intership Repository",
>     "@appName": {
> ```

Is using this approach allows to change the language on the fly?
___
*[`lib/screens/login_screen.dart` line 6 at r1](https://reviewable.io/reviews/cr-crme/banque_stages/4#-NEui-6o4uLplh-skqCT:-NEui-6o4uLplh-skqCU:bxlkebu) ([raw file](https://github.com/cr-crme/banque_stages/blob/0c33dd257aadaf468611458ca9ba7f8b65bf4889/lib/screens/login_screen.dart#L6)):*
> ```Dart
> 
> import '/common/providers/auth_provider.dart';
> import '/misc/form_service.dart';
> ```

I've seen that for some files now
It feels weird to start the path with a /

**Review by Guibi1 — COMMENTED** [review]
I've seen that they published a PR, but i dont really know what they changed.
Ideally I can drop my commits because the change made to the history is not that important.

> *[Reviewable](https://reviewable.io/reviews/cr-crme/banque_stages/4#-:-NEvR0828VIdPHn-LCSN:b-q1oena)* status: all files reviewed, 6 unresolved discussions (waiting on @pariterre)

___
*[`lib/common/providers/students_provider.dart` line 9 at r1](https://reviewable.io/reviews/cr-crme/banque_stages/4#-NEufV7fCHxb9_0aPYLd:-NEvPry7CzKB8t6T--xZ:b34h9c2) ([raw file](https://github.com/cr-crme/banque_stages/blob/0c33dd257aadaf468611458ca9ba7f8b65bf4889/lib/common/providers/students_provider.dart#L9)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Is `void` a new keyword to ignore this feature? :)
</blockquote></details>

nope but its a path we can expect to never exist on the database... we could also probably put null but i was effrayed that would actually do something
___
*[`lib/common/widgets/activity_type_cards.dart` line 5 at r1](https://reviewable.io/reviews/cr-crme/banque_stages/4#-NEufc3C1DqdzRdbjSLn:-NEvQ8gIDlMCS8m08c-Q:b-d5rd56) ([raw file](https://github.com/cr-crme/banque_stages/blob/0c33dd257aadaf468611458ca9ba7f8b65bf4889/lib/common/widgets/activity_type_cards.dart#L5)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Is this the new recommended way? That looks neat
</blockquote></details>

yup. Dart's vs code extension somehow didnt do it that was until recently
___
*[`lib/common/widgets/main_drawer.dart` line 18 at r1](https://reviewable.io/reviews/cr-crme/banque_stages/4#-NEufnMRCAlIHpIANNPI:-NEvQPgm6GTTmsJFUy8M:b-896fix) ([raw file](https://github.com/cr-crme/banque_stages/blob/0c33dd257aadaf468611458ca9ba7f8b65bf4889/lib/common/widgets/main_drawer.dart#L18)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

As I was discussing with Aurélie, it may happen in the future that the app should be available in english. I therefore suggest that we create a structure that holds all the texts and to refer to that structure, hence regrouping all pieces of text to the same place. Then using a selector the return the right value
</blockquote></details>

Done.
___
*[`lib/localizations/app_en.arb` line 2 at r1](https://reviewable.io/reviews/cr-crme/banque_stages/4#-NEuh30g02ZDoilkvbSQ:-NEvQQqP9Sh9BldkLBWQ:b-896fix) ([raw file](https://github.com/cr-crme/banque_stages/blob/0c33dd257aadaf468611458ca9ba7f8b65bf4889/lib/localizations/app_en.arb#L2)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Oh! There it is... 
</blockquote></details>

Done.
___
*[`lib/localizations/app_en.arb` line 4 at r1](https://reviewable.io/reviews/cr-crme/banque_stages/4#-NEuhi18B6fcDLSstIGe:-NEvQX5O5nMfhyRyq5Qf:bqp6s7w) ([raw file](https://github.com/cr-crme/banque_stages/blob/0c33dd257aadaf468611458ca9ba7f8b65bf4889/lib/localizations/app_en.arb#L4)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Is using this approach allows to change the language on the fly?
</blockquote></details>

Yes it does. By default it follows the system's locale but we could add an option somewhere to choose manually (altho not recommended by flutter)
___
*[`lib/screens/login_screen.dart` line 6 at r1](https://reviewable.io/reviews/cr-crme/banque_stages/4#-NEui-6o4uLplh-skqCT:-NEvQrq9EqhkIHv2KUsN:b-v0laru) ([raw file](https://github.com/cr-crme/banque_stages/blob/0c33dd257aadaf468611458ca9ba7f8b65bf4889/lib/screens/login_screen.dart#L6)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

I've seen that for some files now
It feels weird to start the path with a /
</blockquote></details>

the / start the path at the root of the lib folder

**Pull request closed without merging**
